---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: todo
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "todo"
    - name: MYSQL_USER
      value: "todo"
    - name: MYSQL_PASSWORD
      value: "todo"
    - name: MYSQL_DATABASE
      value: "todo"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: todo
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
