---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "todo"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "todo"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: todo
spec:
  selector:
    app: grafana
  ports:
    - name: grafana-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer


